scss_files: 'app/assets/stylesheets/*'
severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  # Remove once all project have AutoPrefixer
  VendorPrefix:
    enabled: false

  # Remove after deprecation phase
  ImportantRule:
    enabled: false

  # Potentially remove one day
  NestingDepth:
    max_depth: 4

  SelectorDepth:
    max_depth: 4

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
